### ISSUE TITLE
Your password and confirmation password do not match. Please try again.

### ISSUE THREAD

**Issue by myleslee** [ddspringle/framework-one-secure-auth#9]
I just downloaded the source code and booted it up with CommandBox.  The error comes up upon registration. I can confirm the passwords are identical.

Environment: Lucee 5.2.4+37 + MySQL.

What could be the possible cause of it?

**Comment by ddspringle** [comment]
Not sure, I cannot reproduce the error. You can dump out rc.password and rc.confirm, as well as the compareNoCase( rc.password, rc.confirm ) on line 102 in /home/controllers/main.cfc to show the password, confirmed password and what compareNoCase() between them produces (should be a zero 0).

Try different passwords... possible you're using characters (high ASCII) that are not being handled properly. You could also change line 101 to use a different comparison (e.g. rc.password eq rc.confirm) instead of compareNoCase() if it turns out compareNoCase() won't return 0 with the characters you're using. 

I hope that helps and let me know if any of that helps you solve your problem.

**Comment by myleslee** [comment]
Thanks for the hints!  I followed your instruction to dump things at the problem line but everything seemed okay. Then I wasn't able to reproduce the error again. But I'm getting another error that I don't seem to pin down the cause. So I'm closing the issue and open another one. Thanks again!
